apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: peterskriba/reservation-ufe
    newName: peterskriba/reservation-ufe
    newTag: 1.2.5 #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
  - name: annotaid/reservation-webapi
    newName: annotaid/reservation-webapi
    newTag: 1.2.0

replacements:
  - targets:
      - select:
          group: fe.milung.eu
          version: v1
          kind: WebComponent
          name: xskriba-xbublavy-reservation-ufe
        fieldPaths:
          - spec.hash-suffix
    source:
      version: v1
      kind: Deployment
      name: xskriba-xbublavy-reservation-ufe-deployment
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ':'
        index: 1
