apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 'https://github.com/wac24-xbublavy-xskriba/xskriba-xbublavy-reservation-webapi//deployments/kustomize/install' # ?ref=v1.0.1
