apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: peterskriba/reservation-ufe
    newName: peterskriba/reservation-ufe # {"$imagepolicy":  "wac-hospital:reservation-ufe:name"}
    newTag: main.20240525.2009 # {"$imagepolicy": "wac-hospital:reservation-ufe:tag"}
  - name: milung/ufe-controller
    newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
    newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
  - name: annotaid/reservation-webapi
    newName: annotaid/reservation-webapi # {"$imagepolicy":  "wac-hospital:reservation-webapi:name"}
    newTag: main.20240525.2017 # {"$imagepolicy": "wac-hospital:reservation-webapi:tag"}
