apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace:
  wac-hospital # chceme tieto objekty umiestniť do `wac-hospital` namespace
  # tento zapis preťaží hodnoty "namespace" vo všetkých objektoch

commonLabels:
  app.kubernetes.io/part-of: wac-hospital

resources:
  - ../../../apps/xskriba-xbublavy-reservation-ufe
  - ../../../apps/xskriba-xbublavy-reservation-webapi
  - ../../../apps/mongo-express

components:
  - ../../../components/version-developers
  - https://github.com/wac24-xbublavy-xskriba/xskriba-xbublavy-reservation-webapi//deployments/kustomize/components/mongodb

patches:
  - path: patches/reservation-webapi.service.yaml
